// MIT License
// 
// Copyright (c) 2022 Next.e.GO Mobile SE, Aachen, Germany (https://e-go-mobile.com/)
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// this data has been generated by
// https://randomuser.me/
export const exampleUsers = [
    {
        "firstName": "Jeff",
        "lastName": "Ramos",
        "email": "jeff.ramos@example.com"
    },
    {
        "firstName": "Kasper",
        "lastName": "Olsen",
        "email": "kasper.olsen@example.com"
    },
    {
        "firstName": "Craig",
        "lastName": "Vasquez",
        "email": "craig.vasquez@example.com"
    },
    {
        "firstName": "Eugenio",
        "lastName": "Vega",
        "email": "eugenio.vega@example.com"
    },
    {
        "firstName": "Esperanza",
        "lastName": "Flores",
        "email": "esperanza.flores@example.com"
    },
    {
        "firstName": "Ava",
        "lastName": "Mccoy",
        "email": "ava.mccoy@example.com"
    },
    {
        "firstName": "Aiden",
        "lastName": "Singh",
        "email": "aiden.singh@example.com"
    },
    {
        "firstName": "Maurizio",
        "lastName": "Henry",
        "email": "maurizio.henry@example.com"
    },
    {
        "firstName": "Christina",
        "lastName": "Rodriguez",
        "email": "christina.rodriguez@example.com"
    },
    {
        "firstName": "Jidde",
        "lastName": "Vleugels",
        "email": "jidde.vleugels@example.com"
    },
    {
        "firstName": "Mille",
        "lastName": "Jensen",
        "email": "mille.jensen@example.com"
    },
    {
        "firstName": "Jonas",
        "lastName": "Lecomte",
        "email": "jonas.lecomte@example.com"
    },
    {
        "firstName": "Yentl",
        "lastName": "Ten Hoeve",
        "email": "yentl.tenhoeve@example.com"
    },
    {
        "firstName": "Cassandra",
        "lastName": "Webb",
        "email": "cassandra.webb@example.com"
    },
    {
        "firstName": "Phillip",
        "lastName": "West",
        "email": "phillip.west@example.com"
    },
    {
        "firstName": "Luize",
        "lastName": "Fogaça",
        "email": "luize.fogaca@example.com"
    },
    {
        "firstName": "Vincent",
        "lastName": "Lo",
        "email": "vincent.lo@example.com"
    },
    {
        "firstName": "Pierre-Alain",
        "lastName": "Rousseau",
        "email": "pierre-alain.rousseau@example.com"
    },
    {
        "firstName": "Romy",
        "lastName": "Brunet",
        "email": "romy.brunet@example.com"
    },
    {
        "firstName": "Marina",
        "lastName": "Pascual",
        "email": "marina.pascual@example.com"
    },
    {
        "firstName": "Nicolas",
        "lastName": "Moreau",
        "email": "nicolas.moreau@example.com"
    },
    {
        "firstName": "Jitze",
        "lastName": "De Winter",
        "email": "jitze.dewinter@example.com"
    },
    {
        "firstName": "Brad",
        "lastName": "Sutton",
        "email": "brad.sutton@example.com"
    },
    {
        "firstName": "Nevaeh",
        "lastName": "Morris",
        "email": "nevaeh.morris@example.com"
    },
    {
        "firstName": "Bartel",
        "lastName": "Renkema",
        "email": "bartel.renkema@example.com"
    },
    {
        "firstName": "Jessica",
        "lastName": "Little",
        "email": "jessica.little@example.com"
    },
    {
        "firstName": "Zoe",
        "lastName": "Snyder",
        "email": "zoe.snyder@example.com"
    },
    {
        "firstName": "Albert",
        "lastName": "Wagner",
        "email": "albert.wagner@example.com"
    },
    {
        "firstName": "النا",
        "lastName": "نكو نظر",
        "email": "ln.nkwnzr@example.com"
    },
    {
        "firstName": "Maria",
        "lastName": "Sullivan",
        "email": "maria.sullivan@example.com"
    },
    {
        "firstName": "آریا",
        "lastName": "کریمی",
        "email": "ary.khrymy@example.com"
    },
    {
        "firstName": "Antoine",
        "lastName": "Adam",
        "email": "antoine.adam@example.com"
    },
    {
        "firstName": "Elijah",
        "lastName": "West",
        "email": "elijah.west@example.com"
    },
    {
        "firstName": "Teobaldo",
        "lastName": "Dias",
        "email": "teobaldo.dias@example.com"
    },
    {
        "firstName": "Ali",
        "lastName": "Özkök",
        "email": "ali.ozkok@example.com"
    },
    {
        "firstName": "Erik",
        "lastName": "Craig",
        "email": "erik.craig@example.com"
    },
    {
        "firstName": "Pieta",
        "lastName": "Houtveen",
        "email": "pieta.houtveen@example.com"
    },
    {
        "firstName": "حسین",
        "lastName": "قاسمی",
        "email": "hsyn.qsmy@example.com"
    },
    {
        "firstName": "Chris",
        "lastName": "Gibson",
        "email": "chris.gibson@example.com"
    },
    {
        "firstName": "Enzo",
        "lastName": "Smaal",
        "email": "enzo.smaal@example.com"
    },
    {
        "firstName": "Mylène",
        "lastName": "Otto",
        "email": "mylene.otto@example.com"
    },
    {
        "firstName": "Aada",
        "lastName": "Sakala",
        "email": "aada.sakala@example.com"
    },
    {
        "firstName": "Daniel",
        "lastName": "Sørensen",
        "email": "daniel.sorensen@example.com"
    },
    {
        "firstName": "Teresa",
        "lastName": "Ryan",
        "email": "teresa.ryan@example.com"
    },
    {
        "firstName": "كيان",
        "lastName": "گلشن",
        "email": "kyn.glshn@example.com"
    },
    {
        "firstName": "George",
        "lastName": "Howard",
        "email": "george.howard@example.com"
    },
    {
        "firstName": "ملینا",
        "lastName": "سالاری",
        "email": "mlyn.slry@example.com"
    },
    {
        "firstName": "Julia",
        "lastName": "Jones",
        "email": "julia.jones@example.com"
    },
    {
        "firstName": "Rosária",
        "lastName": "Gomes",
        "email": "rosaria.gomes@example.com"
    },
    {
        "firstName": "Pinja",
        "lastName": "Korpela",
        "email": "pinja.korpela@example.com"
    },
    {
        "firstName": "Jessica",
        "lastName": "Stone",
        "email": "jessica.stone@example.com"
    },
    {
        "firstName": "Ayan",
        "lastName": "Nordby",
        "email": "ayan.nordby@example.com"
    },
    {
        "firstName": "Leo",
        "lastName": "Harrison",
        "email": "leo.harrison@example.com"
    },
    {
        "firstName": "Gudrun",
        "lastName": "Pagel",
        "email": "gudrun.pagel@example.com"
    },
    {
        "firstName": "William",
        "lastName": "Meunier",
        "email": "william.meunier@example.com"
    },
    {
        "firstName": "Hayo",
        "lastName": "Dorgelo",
        "email": "hayo.dorgelo@example.com"
    },
    {
        "firstName": "Erik",
        "lastName": "Payne",
        "email": "erik.payne@example.com"
    },
    {
        "firstName": "Alexandre",
        "lastName": "Roy",
        "email": "alexandre.roy@example.com"
    },
    {
        "firstName": "Kristina",
        "lastName": "Schmidt",
        "email": "kristina.schmidt@example.com"
    },
    {
        "firstName": "Miro",
        "lastName": "Hannula",
        "email": "miro.hannula@example.com"
    },
    {
        "firstName": "Gökhan",
        "lastName": "Baturalp",
        "email": "gokhan.baturalp@example.com"
    },
    {
        "firstName": "Virginie",
        "lastName": "Guillaume",
        "email": "virginie.guillaume@example.com"
    },
    {
        "firstName": "Koray",
        "lastName": "Akyüz",
        "email": "koray.akyuz@example.com"
    },
    {
        "firstName": "Zachary",
        "lastName": "Singh",
        "email": "zachary.singh@example.com"
    },
    {
        "firstName": "Avery",
        "lastName": "White",
        "email": "avery.white@example.com"
    },
    {
        "firstName": "Carter",
        "lastName": "Moore",
        "email": "carter.moore@example.com"
    },
    {
        "firstName": "Marilou",
        "lastName": "Clement",
        "email": "marilou.clement@example.com"
    },
    {
        "firstName": "Iida",
        "lastName": "Haataja",
        "email": "iida.haataja@example.com"
    },
    {
        "firstName": "Asta",
        "lastName": "Poulsen",
        "email": "asta.poulsen@example.com"
    },
    {
        "firstName": "ایلیا",
        "lastName": "کریمی",
        "email": "yly.khrymy@example.com"
    },
    {
        "firstName": "Gül",
        "lastName": "Elmastaşoğlu",
        "email": "gul.elmastasoglu@example.com"
    },
    {
        "firstName": "Roope",
        "lastName": "Salonen",
        "email": "roope.salonen@example.com"
    },
    {
        "firstName": "Riaz",
        "lastName": "Urlings",
        "email": "riaz.urlings@example.com"
    },
    {
        "firstName": "Kester",
        "lastName": "Arslan",
        "email": "kester.arslan@example.com"
    },
    {
        "firstName": "Mohini",
        "lastName": "Kanters",
        "email": "mohini.kanters@example.com"
    },
    {
        "firstName": "Sannah",
        "lastName": "Falch",
        "email": "sannah.falch@example.com"
    },
    {
        "firstName": "Matilda",
        "lastName": "Williams",
        "email": "matilda.williams@example.com"
    },
    {
        "firstName": "Joona",
        "lastName": "Leino",
        "email": "joona.leino@example.com"
    },
    {
        "firstName": "Margaux",
        "lastName": "Blanc",
        "email": "margaux.blanc@example.com"
    },
    {
        "firstName": "Hannah",
        "lastName": "Margaret",
        "email": "hannah.margaret@example.com"
    },
    {
        "firstName": "Emily",
        "lastName": "Watts",
        "email": "emily.watts@example.com"
    },
    {
        "firstName": "Arvin",
        "lastName": "Aasberg",
        "email": "arvin.aasberg@example.com"
    },
    {
        "firstName": "Harper",
        "lastName": "Roy",
        "email": "harper.roy@example.com"
    },
    {
        "firstName": "امیر",
        "lastName": "سلطانی نژاد",
        "email": "myr.sltnynjd@example.com"
    },
    {
        "firstName": "Oya",
        "lastName": "Erberk",
        "email": "oya.erberk@example.com"
    },
    {
        "firstName": "Concepcion",
        "lastName": "Nuñez",
        "email": "concepcion.nunez@example.com"
    },
    {
        "firstName": "Naomi",
        "lastName": "Roberts",
        "email": "naomi.roberts@example.com"
    },
    {
        "firstName": "Harrison",
        "lastName": "Hughes",
        "email": "harrison.hughes@example.com"
    },
    {
        "firstName": "Elida",
        "lastName": "Veland",
        "email": "elida.veland@example.com"
    },
    {
        "firstName": "بهاره",
        "lastName": "نكو نظر",
        "email": "bhrh.nkwnzr@example.com"
    },
    {
        "firstName": "Mila",
        "lastName": "Smith",
        "email": "mila.smith@example.com"
    },
    {
        "firstName": "یسنا",
        "lastName": "صدر",
        "email": "ysn.sdr@example.com"
    },
    {
        "firstName": "Emanuel",
        "lastName": "Louis",
        "email": "emanuel.louis@example.com"
    },
    {
        "firstName": "Francesca",
        "lastName": "Horn",
        "email": "francesca.horn@example.com"
    },
    {
        "firstName": "Iggy",
        "lastName": "Soekhoe",
        "email": "iggy.soekhoe@example.com"
    },
    {
        "firstName": "Onur",
        "lastName": "Kıraç",
        "email": "onur.kirac@example.com"
    },
    {
        "firstName": "Meral",
        "lastName": "Orbay",
        "email": "meral.orbay@example.com"
    },
    {
        "firstName": "دانیال",
        "lastName": "مرادی",
        "email": "dnyl.mrdy@example.com"
    },
    {
        "firstName": "Gerlind",
        "lastName": "Janßen",
        "email": "gerlind.janssen@example.com"
    },
    {
        "firstName": "Emine",
        "lastName": "Acker",
        "email": "emine.acker@example.com"
    }
]
